version: '3'
services:
  back:
    build: .
    image: davtalks-gitops-back:latest
    container_name: davtalks-gitops-back
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: 'staging'
    expose:
      - 3000